name: .NET

on:
  push:
    branches: [ "nevein25-patch-1" ]
  pull_request:
    branches: [ "nevein25-patch-1" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore src/E-Taberna.sln

    - name: Build
      run: dotnet build src/E-Taberna.sln --no-restore --configuration Release

    - name: Test
      run: dotnet test src/E-Taberna.sln --no-build --verbosity normal
